### PR TITLE
metanorma/metanorma-build-scripts#18 add ruby 2.6 to CI matrix

### PR DESCRIPTION
**Pull request by CAMOBAP795**

### CODE REVIEW

**Comment by ronaldtse** [comment]
@CAMOBAP795 please update the Nokogiri dependency here for this PR. Thanks!

**Comment by ronaldtse** [comment]
@CAMOBAP795 can you relax the Nokogiri dependency here so that we can merge? Thanks.

**Comment by CAMOBAP795** [comment]
@ronaldtse done

**Comment by ronaldtse** [comment]
Thanks, @CAMOBAP795 feel free to merge when all passing.

**Comment by ronaldtse** [comment]
@CAMOBAP795 which gems do we have that lock Nokogiri dependencies? We should hopefully only have 1 or max 2 gems that have this requirement. I can't imagine other gems needing to lock Nokogiri.

**Comment by CAMOBAP795** [comment]
@ronaldtse I purpose to keep version here https://github.com/metanorma/relaton-bib/blob/master/relaton-bib.gemspec I have just removed it from https://github.com/metanorma/iso-bib-item/pull/11/files too

**Pull request merged**
